name: auth
description: Auth Service
version: 1.0.0
# repository: https://github.com/biouri/itproduct-auth

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0
  conduit_postgresql: ^4.4.0
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
